workflows:
  ios-build:
    name: iOS Build Workflow
    instance_type: mac_mini_m1
    environment:
      xcode: latest
      vars:
        DOTNET_VERSION: 8.0.100 # Kullanılacak .NET SDK versiyonu
      ios_signing:
        distribution_type: ad_hoc # app_store, ad_hoc, development, enterprise
        bundle_identifier: com.eas.omacalculator # Uygulamanın Bundle ID'si
    scripts:
      - name: Check if code signing certificates are installed
        script: |
            security find-identity -v -p codesigning
            if [ $? -ne 0 ]; then
              echo "No valid code signing certificates found!"
              exit 1
            fi
      - name: Install .NET SDK
        script: |
          wget https://dot.net/v1/dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh -c 8.0 --install-dir $HOME/.dotnet
          echo 'export PATH=$HOME/.dotnet:$PATH' >> $HOME/.bash_profile
          source $HOME/.bash_profile
      - name: Install MAUI Workloads
        script: |
          export PATH=$HOME/.dotnet:$HOME/.dotnet/tools:$PATH
          dotnet workload install maui-ios --ignore-failed-sources
          dotnet workload restore
          dotnet --info
      - name: Check Installed Workloads
        script: |
          export PATH=$HOME/.dotnet:$HOME/.dotnet/tools:$PATH
          dotnet workload list
      - name: Check .NET SDK
        script: |
          export PATH=$HOME/.dotnet:$PATH
          dotnet --info
      - name: Restore Dependencies
        script: |
          export PATH=$HOME/.dotnet:$PATH
          dotnet restore
      - name: Build .NET MAUI iOS App
        script: |
          export PATH=$HOME/.dotnet:$PATH
          dotnet publish -f:net8.0-ios -c:Release -p:RuntimeIdentifier=ios-arm64 -p:ArchiveOnBuild=true -p:BuildIpa=true
    artifacts:
      - $(find . -name "*.ipa")
