workflows:
  ios-release:
    name: iOS Release Workflow
    instance_type: mac_mini_m1
    environment:
      groups:
        - apple_credentials # Codemagic’de tanımladığın değişkenler
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Restore dependencies
        script: |
          nuget restore
      - name: Build .NET MAUI iOS app
        script: |
          dotnet publish -f:net8.0-ios -c:Release -p:RuntimeIdentifier=ios-arm64 -p:ArchiveOnBuild=true -p:BuildIpa=true
      - name: Export .ipa for TestFlight
        script: |
          mkdir -p build_output
          cp -R "$(find . -name '*.ipa')" build_output/
    artifacts:
      - build_output/*.ipa
    publishing:
      app_store_connect:
        auth: integration # API Key yerine "integration" olmalı
        submit_to_testflight: true
