workflows:
  ios-release:
    name: iOS Release Workflow
    instance_type: mac_mini_m1
    environment:
      xcode: latest
      vars:
        DOTNET_VERSION: 8.0.100 # Kullanılacak .NET SDK versiyonu
    integrations:
      app_store_connect: ea admin
    scripts:
      - name: Install .NET SDK
        script: |
          wget https://dot.net/v1/dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh -c 8.0 --install-dir $HOME/.dotnet
          echo 'export PATH=$HOME/.dotnet:$PATH' >> $HOME/.bash_profile
          source $HOME/.bash_profile
      - name: Install MAUI Workloads
        script: |
          export PATH=$HOME/.dotnet:$HOME/.dotnet/tools:$PATH
          dotnet workload install maui-ios --ignore-failed-sources
          dotnet workload restore
          dotnet --info
      - name: Check Installed Workloads
        script: |
          export PATH=$HOME/.dotnet:$HOME/.dotnet/tools:$PATH
          dotnet workload list
      - name: Check .NET SDK
        script: |
          export PATH=$HOME/.dotnet:$PATH
          dotnet --info
      - name: Restore Dependencies
        script: |
          export PATH=$HOME/.dotnet:$PATH
          dotnet restore
            - name: Import certificate and provisioning profile
        script: |
          # Provisioning Profile'ı tanımla
          echo $PROVISIONING_PROFILE | base64 --decode > /tmp/profile.mobileprovision
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp /tmp/profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

          # Keychain'e sertifikayı ekle
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          echo $CERTIFICATE | base64 --decode > /tmp/certificate.p12
          security import /tmp/certificate.p12 -k build.keychain -P "$CERTIFICATE_PASSWORD" -T /usr/bin/codesign

          # Keychain erişimini düzenle
          security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain
          security list-keychains -d user -s build.keychain
          security find-identity -p codesigning -v
          
      - name: Build .NET MAUI iOS App
        script: |
          export PATH=$HOME/.dotnet:$PATH
          dotnet publish -f:net8.0-ios -c:Release -p:RuntimeIdentifier=ios-arm64 -p:ArchiveOnBuild=true -p:BuildIpa=true
    artifacts:
      - $(find . -name "*.ipa")
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
