workflows:
  ios-release:
    name: iOS Release Workflow
    instance_type: mac_mini_m1
    environment:
      groups:
        - apple_credentials # API Key değişkenlerini Codemagic dashboard'dan ayarla
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Restore dependencies
        script: |
          nuget restore
      - name: Build .NET MAUI iOS app
        script: |
          dotnet publish -f:net8.0-ios -c:Release -p:RuntimeIdentifier=ios-arm64 -p:ArchiveOnBuild=true -p:BuildIpa=true
      - name: Export .ipa for TestFlight
        script: |
          mkdir -p build_output
          cp -R "$(find . -name '*.ipa')" build_output/
    artifacts:
      - build_output/*.ipa
    app_store_connect:
      auth: api_key
      key_id: $APP_STORE_KEY_ID # Codemagic'de tanımladığın değişkenleri kullan
      issuer_id: $APP_STORE_ISSUER_ID
      key: $APP_STORE_API_KEY_P8
    publishing:
      app_store_connect:
        auth: api_key
        submit_to_testflight: true # TestFlight'a otomatik yükler
